# All site-specific settings for bassi.li

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md

footer: 'find me on <a href="https://www.linkedin.com/in/michael-bassili/">linkedin</a>'

style: hacker # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
