markdown:    kramdown
exclude:     ['README.md', vendor]
version:     2.0.0
username:    LaputanMachines
repo:        LaputanMachines.github.io
branch:      master
title:       Homepage | Michael Bassili
author:      Michael Bassili
url:         https://bassi.li
description:  Howdy! My name is Michael, and I'm many things. I work a day-job as a programmer. I moonlight as a drummer, journalist, and writer. If you want to hire me to do one of these things, shoot me an email! Otherwise, feel free to browse the site. I try to keep my portfolios up-to-date. 
source:      .
destination: _site
highlighter: rouge
linenos:     true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-watch

jekyll_admin:
  hidden_links:
    - datafiles

highlight:
  linenos: true

highlight_options:
  linenos: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
